# Generated by Django 4.0.4 on 2022-09-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(choices=[(0, "Draft"), (1, "Publish")], default=1),
        ),
    ]
