# Generated by Django 4.0.4 on 2022-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="blog_category",
            field=models.CharField(default="uncategorized", max_length=200),
        ),
    ]
