# Generated by Django 4.0.4 on 2022-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "client_name",
                    models.CharField(
                        help_text="It's the name of the client", max_length=200, verbose_name="Client's name"
                    ),
                ),
                (
                    "is_live_account",
                    models.CharField(
                        help_text="Shows whether the added account is live or demo",
                        max_length=200,
                        verbose_name="Live or Demo account",
                    ),
                ),
                ("account_number", models.CharField(max_length=50, verbose_name="IB's account number")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "email_address",
                    models.EmailField(
                        blank=True,
                        default="example@gmail.com",
                        help_text="It is the email address of the person",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "telegram_nickname",
                    models.CharField(
                        blank=True, help_text="Here is client's telegram", max_length=100, verbose_name="Telegram"
                    ),
                ),
                (
                    "linkedin_profile",
                    models.CharField(
                        blank=True,
                        help_text="Here is the link to contact's LinkedIn profile",
                        max_length=500,
                        verbose_name="LinkedIn",
                    ),
                ),
            ],
        ),
    ]
